export const DATA_LT_D_Filters = {
  priceRange: {
    buttonName: "Price",
    nameOnCard: "Price per month",
    minimum: "500",
    maximum: "10000",
    maxSpecialCharacter: "+",
    addCharacterMaxSpecialCharacter: true,
    whichMeasure: "$",
    addCharacter: "toLeft",
  },

  duration: {
    buttonName: "Duration",
    minimum: "1",
    maximum: "12",
    maxSpecialCharacter: "+",
    minSpecialCharacter: "-",
    addCharacterMaxSpecialCharacter: "toLeft",
    addCharacterMinSpecialCharacter: "toLeft",
    whichMeasure: "months",
    addCharacter: "toRight",
  },

  houseType: {
    buttonName: "Type",
    buttonOnCard: "Housing type",
    categoriesToDisplay: ["Female only", "Male only", "Coed"],
  },
  accommodations: {
    buttonName: "Accommodations",
    categoriesToDisplay: [
      "Shared",
      "Private",
      "Dormitories",
      "Hotels",
      "Hostels",
      "Motels",
      "Bed and Breakfast (B&B)",
      "Guesthouses",
      "Vacations Rentals",
      "Resorts",
      "Campgrounds",
      "Apartments",
    ],
  },
  moreFilters: {
    specialties: {
      buttonName: "Specialties",
      categoriesToDisplay: [
        "Behavior therapy",
        "Speech & Language",
        "Occupational",
        "Physical Therapy",
        "Psychology",
        "Art Therapy",
        "Music Therapy",
        "Play Therapy",
        "Geriatric Therapy",
        "Family Therapy",
        "Dance therapy",
        "Pain Management Therapy",
        "Sexual Abuse Therapy",
        "Post-Traumatic Stress Disorder",
        "Eating Dirorder Therapy",
        "Depression Therapy",
        "Anxiety Therapy",
        "Couples Therapy",
        "Trauma Therapy",
      ],
    },
  },
}
