export const mongoData = {
  record000: {
    distance: 1.3949532508850098,
    mongo: {
      "Accounting Expenses": "$500 to $1,000",
      Address: "407 W Broadway Ave",
      "Advertising  Expenses": "Less than $5,000",
      "Carrier Route": "C005",
      City: "Forest Lake",
      "Company Description":
        "Established IN 2002, Beyond The Brain Therapies Inc. Is A Forest Lake-Based Wellness Center Offering A Comprehensive Range Of Services To Support Mental And Emotional Health. We Moved From Town Square To The Brick House On Broadway To Expand Out Team Of Licensed Professionals Into A Relaxed Family Friendly Setting. We Utilize Various Approaches, Including Cbt, Dbt, Brainspotting, Alternative Health Options, Biofeedback And Trauma Therapy, To Address A Wide Range Of Concerns. From Chronic Pain To Relationship Challenges, Beyond The Brain Therapies Inc. Helps Individuals And Families Navigate Life's Hurdles And Achieve Their Goals.",
      "Company Name": "Beyond The Brain Therapies Inc",
      "Computer Expenses": "$1,000 to $2,500",
      "Contract Labor Expenses": "$1,000 to $10,000",
      "Corporate Employee Size Actual": 0,
      "Corporate Sales Volume Actual": "$0",
      County: "Washington",
      "Credit Score Alpha": "B+",
      "Delivery Point Barcode": 79.0,
      "Executive First Name": "Debra",
      "Executive First Name 1": "Debra",
      "Executive First Name 2": "Yvonne",
      "Executive Gender": "Female",
      "Executive Gender 1": "Female",
      "Executive Gender 2": "Female",
      "Executive Last Name": "Nelson",
      "Executive Last Name 1": "Nelson",
      "Executive Last Name 2": "Kutzer",
      "Executive Title": "Owner",
      "Executive Title 1": "Owner",
      "Executive Title 2": "Other",
      "Firm or Individual": 2,
      "Fortune 1000 Ranking": 0,
      "Friday Close": "1800",
      "Friday Open": "1000",
      "Government Office": 0,
      "Home Business": "No",
      "IUSA Number": "74-742-5180",
      "Insurance Expenses": "Less than $2,500",
      "Last Updated On": 202403,
      Latitude: 45.27954,
      "Legal Expenses": "Less than $500",
      "Location Centerpoint": "Parcel",
      "Location Employee Size Actual": 5,
      "Location Employee Size Range": "5 to 9",
      "Location Sales Volume Actual": "$265,000",
      "Location Sales Volume Range": "Less Than $500,000",
      "Location Type": "Single Loc",
      Longitude: -92.989122,
      "Management/Administration Expenses": "$5,000 to $10,000",
      "Metro Area": "Minn-Blmt, MN-WI",
      "Monday Close": "2100",
      "Monday Open": "1000",
      "NAICS 1": 62133004,
      "NAICS 1 Description":
        "Offices Of Mental Health Practitioners (Except Phy",
      "NAICS 2": 62221001.0,
      "NAICS 2 Description": "Psychiatric And Substance Abuse Hospitals",
      "NAICS 3": 62411004.0,
      "NAICS 3 Description": "Child And Youth Services",
      "Office Supplies Expense": "$10,000 to $20,000",
      "Own or Lease": "Own",
      "Package Container Expense": "Less than $500",
      "Parent IUSA Number": 0,
      "Payroll and Benefits Expenses": "Less than $100,000",
      "Phone Number Combined": "(651) 408-3174",
      "Primary NAICS": 62133004,
      "Primary NAICS Description":
        "Offices Of Mental Health Practitioners (Except Phy",
      "Primary SIC Code": 832227,
      "Primary SIC Description": "Mental Health Counselors",
      "Primary SIC Year Appeared": 2020,
      "Purchase Print Expenses": "$1,000 to $2,500",
      "Rent Expenses": "$25,000 to $50,000",
      "SIC Code 1": 832227,
      "SIC Code 1 Description": "Mental Health Counselors",
      "SIC Code 2": 806301.0,
      "SIC Code 2 Description": "Mental Health Services",
      "SIC Code 3": 832201.0,
      "SIC Code 3 Description": "Counseling Services",
      "Saturday Open": "Closed",
      "Square Footage": "20,000 - 39,999",
      State: "MN",
      "Subsidiary IUSA Number": 0,
      "Sunday Open": "Closed",
      "Telcom Expenses": "Less than $2,000",
      "Thursday Close": "2100",
      "Thursday Open": "1000",
      "Tuesday Close": "2100",
      "Tuesday Open": "1000",
      "Type of Business": "Private",
      Website: "Beyondthebraintherapies.Com",
      "Wednesday Close": "2100",
      "Wednesday Open": "1000",
      "Years In Database": 5,
      "ZIP Code": 55025,
      "ZIP Four": 1402.0,
    },
    node_id: "c37105b9bd22d227ea4c8f277b4a8530",
    rank: 0.04579935967922211,
    record: "1d4e4c4cced574857ff0d470",
  },
  record001: {
    distance: 1.4437755346298218,
    mongo: {
      "Accounting Expenses": "$500 to $1,000",
      Address: "3019 Colby Ave",
      "Advertising  Expenses": "Less than $5,000",
      "Affiliated Locations": 0,
      "Affiliated Records": 0,
      "Carrier Route": "C035",
      City: "Everett",
      "Company Description":
        "The First Step IN The Treatment Process Is To Complete A Comprehensive Assessment To Determine The Extent Of The Alcohol OR Other Drug Problem And Appropriate Treatment Options. Our Evaluation Not Only Includes An Interview But Also One OR More Research-Based Evaluative Tools, Such As Mast, Dast, Sassi And Asi. Collateral Interviews And Alcohol/Drug Screening May Also Be Employed To Further Support The Assessment Process. If Assessment Is Required For A Legal Proceeding, A Copy Of The Criminal Defense History Will Be Required. To Expedite The Process, The Patient Is To Bring The Criminal Defense History To The Assessment Appointment. Based On The Results Of The Interview And Evaluative Tools, The Findings And Recommendations For Treatment Will Be Explained And The Patient Will Be Given Treatment Referrals IN Keeping With State Laws.Services * Assessments * Outpatient Treatment * Pregnant/Parenting Women * Safe Babies, Safe Moms * Detoxification * Drug Screening * Recovery Housing * Domestic Violence * Adis",
      "Company Name": "Evergreen Recovery Ctr",
      "Computer Expenses": "$500 to $1,000",
      "Contract Labor Expenses": "$1,000 to $10,000",
      "Corporate Employee Size Actual": 0,
      "Corporate Sales Volume Actual": "$0",
      County: "Snohomish",
      "Credit Score Alpha": "B+",
      "Delivery Point Barcode": 192.0,
      "Executive First Name": "Grant",
      "Executive First Name 1": "Grant",
      "Executive Gender": "Male",
      "Executive Gender 1": "Male",
      "Executive Last Name": "Linda",
      "Executive Last Name 1": "Linda",
      "Executive Title": "Manager",
      "Executive Title 1": "Manager",
      "Firm or Individual": 2,
      "Fortune 1000 Ranking": 0,
      "Friday Close": "1700",
      "Friday Open": "0800",
      "Government Office": 0,
      "Home Business": "No",
      "IUSA Number": "74-944-1674",
      "Insurance Expenses": "Less than $2,500",
      "Last Updated On": 202006,
      Latitude: 47.977036,
      "Legal Expenses": "Less than $500",
      "Location Centerpoint": "Parcel",
      "Location Employee Size Actual": 6,
      "Location Employee Size Range": "5 to 9",
      "Location Sales Volume Actual": "$354,000",
      "Location Sales Volume Range": "Less Than $500,000",
      "Location Type": "Single Loc",
      Longitude: -122.20813,
      "Management/Administration Expenses": "$5,000 to $10,000",
      "Metro Area": "Seattle, WA",
      "Monday Close": "1700",
      "Monday Open": "0800",
      "NAICS 1": 62133004,
      "NAICS 1 Description":
        "Offices Of Mental Health Practitioners (Except Phy",
      "NAICS 2": 62419031.0,
      "NAICS 2 Description": "Other Individual And Family Services",
      "NAICS 3": 81331106.0,
      "NAICS 3 Description": "Human Rights Organizations",
      Neighborhood: "Port Gardner",
      "Office Supplies Expense": "$5,000 to $10,000",
      "Own or Lease": "Lease",
      "Package Container Expense": "Less than $500",
      "Parent IUSA Number": 0,
      "Payroll and Benefits Expenses": "Less than $100,000",
      "Phone Number Combined": "(425) 258-2407",
      "Primary NAICS": 62133004,
      "Primary NAICS Description":
        "Offices Of Mental Health Practitioners (Except Phy",
      "Primary SIC Code": 832227,
      "Primary SIC Description": "Mental Health Counselors",
      "Primary SIC Year Appeared": 2020,
      "Purchase Print Expenses": "$1,000 to $2,500",
      "Rent Expenses": "Less than $10,000",
      "SIC Code 1": 832227,
      "SIC Code 1 Description": "Mental Health Counselors",
      "SIC Code 2": 832251.0,
      "SIC Code 2 Description": "Substance Abuse Centers",
      "SIC Code 3": 839921.0,
      "SIC Code 3 Description": "Addiction Treatment Centers",
      "Saturday Open": "Closed",
      "Square Footage": "2,500 - 4,999",
      State: "WA",
      "Subsidiary IUSA Number": 0,
      "Sunday Open": "Closed",
      "Telcom Expenses": "Less than $2,000",
      "Thursday Close": "1700",
      "Thursday Open": "0800",
      "Tuesday Close": "1700",
      "Tuesday Open": "0800",
      "Type of Business": "Private",
      "Utilities Expenses": "$2,000 to $5,000",
      Website: "Evergreenmanor.Org",
      "Wednesday Close": "1700",
      "Wednesday Open": "0800",
      "Years In Database": 5,
      "ZIP Code": 98201,
      "ZIP Four": 4022.0,
    },
    node_id: "c37105b9bd22d227ea4c8f277b4a8530",
    rank: 0.04502888396382332,
    record: "11a458a4b6a9a30266d50099",
  },
  record002: {
    distance: 1.4986720085144043,
    mongo: {
      Address: "1101 Saint Paul St # 405",
      "Advertising  Expenses": "$10,000 to $20,000",
      "Carrier Route": "C029",
      City: "Baltimore",
      "Company Description":
        "David Shapiro Is A No Nonsense Baltimore Personal Injury Law Firm Which Represents Clients IN Baltimore And Surrounding Areas. Our Attorneys Specialize IN Many Facets Of The Legal Word From Medical Malpractice To Dui Cases And Criminal Defense, And Have Over 22 Years Of Combined Litigation Experience. And We Put 100% Of Our Experience, Expertise, Effort, Legal Knowledge, And Our Commitment To Getting Justice For Our Clients. But Our Pledge To Personal Service And Representation Doesn't Just Come To An End With A Signed Check.Many Big Law Firms Like To Advertise Big Cases And Verdicts Because These Cases Mean Theyve Been Paid A Large Sum Of Money. But How Does A Dubious Plan Like This Help You? A Huge Settlement May Look Great On Paper, But After Everyone Has Taken His OR Her Cut Then Youre Probably Not Left With Anywhere Near As Much As What You Wanted OR Felt You Deserved.The Good Thing About Our Firm Is That We Dont Work Just For The Money We Work For You! What Matters Most To US Is Not The Settlement Number But Instead Its About Maximizing The Amount You Can Take Home And Keep For Yourself And Family. Even After You Receive Your Settlement OR Judgment, We Continue To Work For You By Helping You Get The Maximum Value Out Of Your Lawsuit. Were Able To Negotiate With Doctors, Insurance Companies, Even Medicare And/OR Medicaid To Help You Save A Larger Amount Of Your Settlement OR Judgment. Then We Help Advice You On How To Protect That Money So It Will Be Long-Term And When You Need It Most.Our Expansive Services Include: Medical Malpractice Product Liability Wrongful Death Criminal Defense Credit Fraud Car Accident Injury Caseswe Know That After An Injury Money Can Be Extremely Tight, So When You Consult With US We Take Care Of Those Fees For Free. At David Shapiro, We Work On A Contingency Basis -- Meaning We Don't Get Paid Unless You Do. That Means We Won't Delay Your Case Trying To Build Up Annoying And Costly Billable Hours, OR Hurry Into A Trial Unprepared To Get Accumulate Court Fees. We Work Extremely Hard Trying To Get You The Best Possible Results. We Can Come To Your Home, Office, Hospital, Nursing Home OR Whatever Location You Need US To. Just Tell US Where!our Personal Promise To You:at The David Shapiro Law Firm, We Focus On Personal Service. When You Contact US, We Will Always Promptly Call OR Email Back. We Are Constantly Checking Our Messages And Will Get Back To You -- No Matter What. We Are Never Too Busy For The Concerns Of Our Clients.If You OR A Loved One Has Been Hurt, Injured, OR Been Arrested For A Dui OR Anything Else, And You Need Help, Please Call OR Email US Today For A Free Consultation. You Wont Be Sorry You Did!",
      "Company Name": "Law Offices Of David B Shapiro",
      "Computer Expenses": "$5,000 to $10,000",
      "Contract Labor Expenses": "$10,000 to $50,000",
      "Corporate Employee Size Actual": 0,
      "Corporate Sales Volume Actual": "$0",
      County: "Baltimore City",
      "Credit Cards Accepted": "1ADMV",
      "Credit Score Alpha": "A",
      "Delivery Point Barcode": 56.0,
      "Executive First Name": "David B",
      "Executive First Name 1": "David B",
      "Executive Gender": "Male",
      "Executive Gender 1": "Male",
      "Executive Last Name": "Shapiro",
      "Executive Last Name 1": "Shapiro",
      "Executive Title": "Owner",
      "Executive Title 1": "Owner",
      Facebook:
        "https://www.facebook.com/pages/the-law-offices-of-david-b-shapiro/133163626734108",
      "Firm or Individual": 2,
      "Fortune 1000 Ranking": 0,
      "Franchise Description 1": "Personal Injury",
      "Franchise/Specialty Code 2.0": "Bankruptcy",
      "Franchise/Specialty Code 3.0": "Corporate Business",
      "Friday Close": "Open 24 Hours",
      "Friday Open": "Open 24 Hours",
      "Government Office": 8,
      "Home Business": "No",
      "IUSA Number": "71-573-3751",
      "Last Updated On": 202310,
      Latitude: 39.302776,
      "Location Centerpoint": "Parcel",
      "Location Employee Size Actual": 10,
      "Location Employee Size Range": "10 to 19",
      "Location Sales Volume Actual": "$0",
      "Location Type": "Single Loc",
      Longitude: -76.614066,
      "Mailing City": "Baltimore",
      "Mailing State": "MD",
      "Mailing Zip Code": 21202.0,
      "Management/Administration Expenses": "$10,000 to $25,000",
      "Metro Area": "Baltimr-Twsn, MD",
      "Monday Close": "Open 24 Hours",
      "Monday Open": "Open 24 Hours",
      "NAICS 1": 54111002,
      "NAICS 1 Description": "Offices Of Lawyers",
      "NAICS 2": 52429801.0,
      "NAICS 2 Description": "All Other Insurance Related Activities",
      "NAICS 3": 53121003.0,
      "NAICS 3 Description": "Offices Of Real Estate Agents And Brokers",
      "NAICS 4": 54111003.0,
      "NAICS 4 Description": "Offices Of Lawyers",
      "NAICS 5": 54119907.0,
      "NAICS 5 Description": "All Other Legal Services",
      "NAICS 6": 61169204.0,
      "NAICS 6 Description": "Automobile Driving Schools",
      "NAICS 7": 92611001.0,
      "NAICS 7 Description": "Administration Of General Economic Programs",
      Neighborhood: "Mid-Town Belvedere",
      "Office Supplies Expense": "$10,000 to $20,000",
      "Parent IUSA Number": 0,
      "Payroll and Benefits Expenses": "$250,000 to $500,000",
      "Phone Number Combined": "(410) 576-9100",
      "Primary NAICS": 54111002,
      "Primary NAICS Description": "Offices Of Lawyers",
      "Primary SIC Ad Size": "Regular",
      "Primary SIC Code": 811103,
      "Primary SIC Description": "Attorneys",
      "Primary SIC Year Appeared": 2015,
      "Rent Expenses": "$25,000 to $50,000",
      "SIC Code 1": 811103,
      "SIC Code 1 Description": "Attorneys",
      "SIC Code 2": 641124.0,
      "SIC Code 2 Description": "Compensation-Accident Service",
      "SIC Code 3": 653118.0,
      "SIC Code 3 Description": "Real Estate",
      "SIC Code 4": 811101.0,
      "SIC Code 4 Description": "Attorneys Service Bureaus",
      "SIC Code 5": 811198.0,
      "SIC Code 5 Description": "Legal Services",
      "SIC Code 6": 829973.0,
      "SIC Code 6 Description": "Traffic Law Representation",
      "SIC Code 7": 961104.0,
      "SIC Code 7 Description": "City Government-Economic Program Administrati",
      "Saturday Close": "Open 24 Hours",
      "Saturday Open": "Open 24 Hours",
      "Square Footage": "100,000+",
      State: "MD",
      "Subsidiary IUSA Number": 0,
      "Sunday Close": "Open 24 Hours",
      "Sunday Open": "Open 24 Hours",
      "Telcom Expenses": "$5,000 to $20,000",
      "Thursday Close": "Open 24 Hours",
      "Thursday Open": "Open 24 Hours",
      "Toll Free Number Combined": 8005000729.0,
      "Tuesday Close": "Open 24 Hours",
      "Tuesday Open": "Open 24 Hours",
      Twitter: "http://twitter.com/dshapirolaw",
      "Type of Business": "Private",
      "Utilities Expenses": "$5,000 to $10,000",
      Website: "Davidshapiro.Com",
      "Wednesday Close": "Open 24 Hours",
      "Wednesday Open": "Open 24 Hours",
      "Years In Database": 10,
      "ZIP Code": 21202,
      "ZIP Four": 903.0,
    },
    node_id: "72e8c40b52049639186601fdb6f93e99",
    rank: 0.044919420033693314,
    record: "92c763419c4e579a63158e73",
  },
  record003: {
    distance: 1.478140115737915,
    mongo: {
      "Accounting Expenses": "$500 to $1,000",
      Address: "4770 Biscayne Blvd # 1250",
      "Advertising  Expenses": "$5,000 to $10,000",
      "Affiliated Locations": 0,
      "Affiliated Records": 0,
      "Carrier Route": "C066",
      "Census Block Group": 2,
      City: "Miami",
      "Company Description":
        'The Criminal Lawyers Of The Edelstein Firm Are Experienced Criminal Defense Attorneys Who Gained Their Experience As Former Public Defenders And Prosecutors. The Firm\'s Main Office Is IN Miami, Florida With Satellite Offices IN Fort Lauderdale And West Palm Beach. The Managing Parnter, David Edelstein, Is An Experienced Criminal Defense Attorney Representing Clients IN Both State And Federal Courts IN Miami, As Well As Other Jurisdictions Throughout Florida. He Enjoys An "av" Rating By Martindale-Hubbell And Has Been Listed IN Florida Trend Magazine, Superlawyers Magazine, And The South Florida Legal Guide IN The Category Of "criminal Defense.',
      "Company Name": "David M Edelstein PA",
      "Computer Expenses": "$2,500 to $5,000",
      "Contract Labor Expenses": "$1,000 to $10,000",
      "Corporate Employee Size Actual": 0,
      "Corporate Sales Volume Actual": "$0",
      County: "Miami Dade",
      "Credit Cards Accepted": "ADMV",
      "Credit Score Alpha": "B+",
      "Delivery Point Barcode": 1.0,
      "EIN 1": 651020002.0,
      "Executive First Name": "David M",
      "Executive First Name 1": "David M",
      "Executive Gender": "Male",
      "Executive Gender 1": "Male",
      "Executive Last Name": "Edelstein",
      "Executive Last Name 1": "Edelstein",
      "Executive Title": "Owner",
      "Executive Title 1": "Owner",
      Facebook: "https://www.facebook.com/miami.criminal.defense.lawyer",
      "Federal Contractor": "No",
      "Firm or Individual": 2,
      "Fortune 1000 Ranking": 0,
      "Franchise Description 1": "Criminal Justice",
      "Friday Close": "Open 24 Hours",
      "Friday Open": "Open 24 Hours",
      "Government Office": 0,
      "Home Business": "No",
      "IUSA Number": "58-392-1762",
      "Insurance Expenses": "$2,500 to $5,000",
      "Last Updated On": 202310,
      Latitude: 25.818928,
      "Legal Expenses": "$1,000 to $2,500",
      "Legal Name": "DAVID M EDELSTEIN PA",
      "Linked-In": "https://linkedin.com/in/miamicriminallawyer",
      "Location Centerpoint": "Parcel",
      "Location Employee Size Actual": 2,
      "Location Employee Size Range": "1 to 4",
      "Location Sales Volume Actual": "$414,000",
      "Location Sales Volume Range": "Less Than $500,000",
      "Location Type": "Single Loc",
      Longitude: -80.188479,
      "Mailing City": "Miami",
      "Mailing State": "FL",
      "Mailing Zip Code": 33137.0,
      "Management/Administration Expenses": "$2,500 to $5,000",
      "Metro Area": "Miami-Ft Ldr, FL",
      "Monday Close": "Open 24 Hours",
      "Monday Open": "Open 24 Hours",
      "NAICS 1": 54111002,
      "NAICS 1 Description": "Offices Of Lawyers",
      "NAICS 2": 56161108.0,
      "NAICS 2 Description":
        "Investigation And Personal Background Check Servic",
      "NAICS 3": 54111003.0,
      "NAICS 3 Description": "Offices Of Lawyers",
      "NAICS 4": 54119907.0,
      "NAICS 4 Description": "All Other Legal Services",
      Neighborhood: "Tower At Bay Point",
      "Office Supplies Expense": "Less than $5,000",
      "Package Container Expense": "Less than $500",
      "Parent IUSA Number": 0,
      "Payroll and Benefits Expenses": "$100,000 to $250,000",
      "Phone Number Combined": "(305) 538-4545",
      "Primary NAICS": 54111002,
      "Primary NAICS Description": "Offices Of Lawyers",
      "Primary SIC Ad Size": "Bold",
      "Primary SIC Code": 811103,
      "Primary SIC Description": "Attorneys",
      "Primary SIC Year Appeared": 2001,
      "Purchase Print Expenses": "$500 to $1,000",
      "Rent Expenses": "$25,000 to $50,000",
      "SIC Code 1": 811103,
      "SIC Code 1 Description": "Attorneys",
      "SIC Code 2": 738118.0,
      "SIC Code 2 Description": "Law Enforcement Consultants",
      "SIC Code 3": 811101.0,
      "SIC Code 3 Description": "Attorneys Service Bureaus",
      "SIC Code 4": 811198.0,
      "SIC Code 4 Description": "Legal Services",
      "Saturday Close": "Open 24 Hours",
      "Saturday Open": "Open 24 Hours",
      "Square Footage": "2,500 - 4,999",
      State: "FL",
      "Subsidiary IUSA Number": 0,
      "Sunday Close": "Open 24 Hours",
      "Sunday Open": "Open 24 Hours",
      "Telcom Expenses": "$2,000 to $5,000",
      "Thursday Close": "Open 24 Hours",
      "Thursday Open": "Open 24 Hours",
      "Toll Free Number Combined": 8773214545.0,
      "Tuesday Close": "Open 24 Hours",
      "Tuesday Open": "Open 24 Hours",
      Twitter: "https://twitter.com/david_edelstein",
      "Type of Business": "Private",
      "Utilities Expenses": "Less than $2,000",
      Website: "Miami-Criminal-Lawyer.Net",
      "Wednesday Close": "Open 24 Hours",
      "Wednesday Open": "Open 24 Hours",
      "Year Established": 2012.0,
      "Years In Database": 24,
      "ZIP Code": 33137,
      "ZIP Four": 3243.0,
    },
    node_id: "72e8c40b52049639186601fdb6f93e99",
    rank: 0.044249001890420914,
    record: "4bc58f674ae526c5625643e2",
  },
  record004: {
    distance: 1.4794085025787354,
    mongo: {
      "Accounting Expenses": "Over $25,000",
      Address: "21515 Hawthorne Blvd # 720",
      "Advertising  Expenses": "$100,000 to $250,000",
      "Affiliated Locations": 0,
      "Affiliated Records": 0,
      "Carrier Route": "C031",
      "Census Block Group": 2,
      City: "Torrance",
      "Company Description":
        "Bowne Decisionquest IN Torrance, Calif., Is A Company That Provides Specialized Support Services For Lawyers Preparing To Go To Court. For More Than 25 Years, The Principals Of Decisionquest Have Been Retained IN High-Risk, High-Stakes Litigation Spanning A Wide Range Of Industries. The Company Has Consulted On Nearly 13,000 Cases From 14 Offices And Graphics Studios. Decisionquest Professionals Assist Trial Teams And IN-House Counsel IN All 50 States And Foreign Jurisdictions. It Offers A Fresh Perspective About Strategies And Tactics At Every Stage Of The Dispute-Resolution Process. Decisionquest Professionals Are Trained IN The Psychology Of Visual Perception And Help Test And Develop A Visual Strategy For Communicating Persuasively With Judges, Jurors, Arbitrators, Mediation Panels And Regulatory Groups. The Company S Trial Consulting And Research Services Include Venue Evaluation, Bench Study OR Arbitration Panel Study, Damages Analysis And Control, Initial Case Assessment, Jury Profiling And Witness Evaluation.",
      "Company Name": "Decisionquest",
      "Computer Expenses": "Over $50,000",
      "Contract Labor Expenses": "$100,000 to $250,000",
      "Corporate Employee Size Actual": 0,
      "Corporate Sales Volume Actual": "$0",
      County: "Los Angeles",
      "Credit Score Alpha": "B+",
      "Delivery Point Barcode": 951.0,
      "EIN 1": 954556077.0,
      "Executive First Name": "Philip",
      "Executive First Name 1": "Philip",
      "Executive First Name 2": "Susan",
      "Executive First Name 3": "Troy",
      "Executive First Name 4": "Anthony",
      "Executive First Name 5": "Craig",
      "Executive First Name 6": "Troy",
      "Executive First Name 7": "Michael",
      "Executive First Name 8": "Katherine",
      "Executive First Name 9": "Claire",
      "Executive Gender": "Male",
      "Executive Gender 1": "Male",
      "Executive Gender 2": "Female",
      "Executive Gender 3": "Male",
      "Executive Gender 4": "Male",
      "Executive Gender 5": "Male",
      "Executive Gender 6": "Male",
      "Executive Gender 7": "Male",
      "Executive Gender 8": "Female",
      "Executive Gender 9": "Female",
      "Executive Last Name": "Anthony",
      "Executive Last Name 1": "Anthony",
      "Executive Last Name 2": "Fillichio",
      "Executive Last Name 3": "Reddington",
      "Executive Last Name 4": "Falzon",
      "Executive Last Name 5": "Lee",
      "Executive Last Name 6": "Reddington",
      "Executive Last Name 7": "Cobo",
      "Executive Last Name 8": "Kiang",
      "Executive Last Name 9": "Kusano",
      "Executive Title": "President",
      "Executive Title 1": "President",
      "Executive Title 2": "Vice President",
      "Executive Title 3": "Publisher/Editor",
      "Executive Title 4": "Director",
      "Executive Title 5": "Director",
      "Executive Title 6": "Manager",
      "Executive Title 7": "Treasurer",
      "Executive Title 8": "Finance",
      "Executive Title 9": "Other",
      Facebook: "https://www.facebook.com/decisionquest",
      "Fax Number Combined": 3106181122.0,
      "Federal Contractor": "No",
      "Firm or Individual": 2,
      "Fortune 1000 Ranking": 0,
      "Friday Close": "1700",
      "Friday Open": "0900",
      "Government Office": 0,
      "Home Business": "No",
      "IUSA Number": "46-218-2668",
      "Insurance Expenses": "Over $100,000",
      "Last Updated On": 202208,
      Latitude: 33.832993,
      "Legal Expenses": "Over $25,000",
      "Legal Name": "DECISIONQUEST INC",
      "Location Centerpoint": "Parcel",
      "Location Employee Size Actual": 50,
      "Location Employee Size Range": "50 to 99",
      "Location Sales Volume Actual": "$13,194,000",
      "Location Sales Volume Range": "$10-20 Million",
      "Location Type": "Branch",
      Longitude: -118.353713,
      "Mailing City": "Torrance",
      "Mailing State": "CA",
      "Mailing Zip Code": 90503.0,
      "Management/Administration Expenses": "Over $100,000",
      "Metro Area": "LA-Long Bch, CA",
      "Monday Close": "1700",
      "Monday Open": "0900",
      "NAICS 1": 56199001,
      "NAICS 1 Description": "All Other Support Services",
      "NAICS 2": 54111003.0,
      "NAICS 2 Description": "Offices Of Lawyers",
      "Office Supplies Expense": "$100,000 to $250,000",
      "Own or Lease": "Unknown",
      "Package Container Expense": "$500 to $1,000",
      "Parent Company Name": "DECISIONQUEST LLC",
      "Parent IUSA Number": 778307323,
      "Payroll and Benefits Expenses": "$2.5 Million to $10 Million",
      "Phone Number Combined": "(310) 618-9600",
      "Primary NAICS": 56199001,
      "Primary NAICS Description": "All Other Support Services",
      "Primary SIC Code": 738999,
      "Primary SIC Description": "Business Services NEC",
      "Primary SIC Year Appeared": 2012,
      "Purchase Print Expenses": "$10,000 to $25,000",
      "Record Type": "Verified",
      "Rent Expenses": "$100,000 to $250,000",
      "SIC Code 1": 738999,
      "SIC Code 1 Description": "Business Services NEC",
      "SIC Code 2": 811101.0,
      "SIC Code 2 Description": "Attorneys Service Bureaus",
      "Saturday Open": "Closed",
      "Square Footage": "100,000+",
      State: "CA",
      "Subsidiary IUSA Number": 0,
      "Sunday Open": "Closed",
      "Telcom Expenses": "$50,000 to $100,000",
      "Thursday Close": "1700",
      "Thursday Open": "0900",
      "Toll Free Number Combined": 8008875696.0,
      "Tuesday Close": "1700",
      "Tuesday Open": "0900",
      Twitter: "http://twitter.com/dqjurytrial",
      "Type of Business": "Private",
      "Utilities Expenses": "Over $100,000",
      Website: "Decisionquest.Com",
      "Wednesday Close": "1700",
      "Wednesday Open": "0900",
      "Years In Database": 13,
      "ZIP Code": 90503,
      "ZIP Four": 6570.0,
    },
    node_id: "72e8c40b52049639186601fdb6f93e99",
    rank: 0.04395511746406555,
    record: "4bc58f674ae526c562563ef1",
  },
}
