import { randomUUID } from "node:crypto"

export const dummy_data = [
  {
    id: randomUUID(),
    resourceId: `${randomUUID()}_0`,
    entryType: "entry_Type_here",
    recordName: "record_Name_here_1",
    recordSubtitle: "record_Subtitle_here",
    listingType: "Listing_Type_here",
    recordSubtype: "record_Subtype_here_1",
    recordSubtypeBreakdown: "",
    usageOrServiceSettings: "",
    address: [{ city: "city_here", state: "ST" }],
    listingDescription: "",
    parentCompanyDescription: "",
    sic: "",
    naics: "",
    onlinePresence: "",
    contactPerson: "",
    languages: "",
    agesServed: "",
    servicesOffered: "",
    diagnosisServed: "",
    diagnosisNotServed: "",
    symptomsSupported: "",
    symptomsNotSupported: "",
    supportedDDFunctionality: "",
    wheelchairAccessible: true,
    businessHours: "",
    pictures: "",
    videos: "",
    reviews: ["first review", "second review", "third review"],
    reviewTags: "",
    ratings: ["", "", ""],
    faqs: "",
    questionTags: "",
    answerTags: "",
    linkedListings: "",
    singleLocationVsFranchise: "",
    verifiedUnverifiedResource: "",
    price: "",
    paymentOptions: "",
    governmentAffiliation: "",
    goals: "",
    directServices: "",
    administrativeServices: "",
    oneClickIntake: "",
    acceptNewClients: "",
    evaluations: "",
    providesAdditional: "",
    knownFor: "",
    tags: "",
  },
  {
    id: randomUUID(),
    resourceId: `${randomUUID()}_1`,
    entryType: "entry_Type_here",
    recordName: "record_Name_here_2",
    recordSubtitle: "record_Subtitle_here",
    listingType: "Listing_Type_here",
    recordSubtype: "record_Subtype_here_2",
    recordSubtypeBreakdown: "",
    usageOrServiceSettings: "",
    address: [{ city: "city_here", state: "ST" }],
    listingDescription: "",
    parentCompanyDescription: "",
    sic: "",
    naics: "",
    onlinePresence: "",
    contactPerson: "",
    languages: "",
    agesServed: "",
    servicesOffered: "",
    diagnosisServed: "",
    diagnosisNotServed: "",
    symptomsSupported: "",
    symptomsNotSupported: "",
    supportedDDFunctionality: "",
    wheelchairAccessible: true,
    businessHours: "",
    pictures: "",
    videos: "",
    reviews: ["first review", "second review", "third review"],
    reviewTags: "",
    ratings: ["", "", ""],
    faqs: "",
    questionTags: "",
    answerTags: "",
    linkedListings: "",
    singleLocationVsFranchise: "",
    verifiedUnverifiedResource: "",
    price: "",
    paymentOptions: "",
    governmentAffiliation: "",
    goals: "",
    directServices: "",
    administrativeServices: "",
    oneClickIntake: "",
    acceptNewClients: "",
    evaluations: "",
    providesAdditional: "",
    knownFor: "",
    tags: "",
  },
  {
    id: randomUUID(),
    resourceId: `${randomUUID()}_1`,
    entryType: "entry_Type_here",
    recordName: "record_Name_here_3",
    recordSubtitle: "record_Subtitle_here",
    listingType: "Listing_Type_here",
    recordSubtype: "record_Subtype_here_3",
    recordSubtypeBreakdown: "",
    usageOrServiceSettings: "",
    address: [{ city: "city_here", state: "ST" }],
    listingDescription: "",
    parentCompanyDescription: "",
    sic: "",
    naics: "",
    onlinePresence: "",
    contactPerson: "",
    languages: "",
    agesServed: "",
    servicesOffered: "",
    diagnosisServed: "",
    diagnosisNotServed: "",
    symptomsSupported: "",
    symptomsNotSupported: "",
    supportedDDFunctionality: "",
    wheelchairAccessible: true,
    businessHours: "",
    pictures: "",
    videos: "",
    reviews: ["first review", "second review", "third review"],
    reviewTags: "",
    ratings: ["", "", ""],
    faqs: "",
    questionTags: "",
    answerTags: "",
    linkedListings: "",
    singleLocationVsFranchise: "",
    verifiedUnverifiedResource: "",
    price: "",
    paymentOptions: "",
    governmentAffiliation: "",
    goals: "",
    directServices: "",
    administrativeServices: "",
    oneClickIntake: "",
    acceptNewClients: "",
    evaluations: "",
    providesAdditional: "",
    knownFor: "",
    tags: "",
  },
]
