export const enum CLASSNAME_ISDIAGNOSIS {
  DIAGNOSIS = "DIAGNOSIS",
  DIAGNOSIS_SPAN = "DIAGNOSIS_SPAN",
  BOLD = "BOLD",
  IN_SYMPTOMS = "IN_SYMPTOMS",
  SUGGESTION = "SUGGESTION",
  SUGGESTION_LI = "SUGGESTION_LI"

}
