export const ALL_ROUTES = {
  ORG: "org",
  RESULTS: "results",
  DETAIL: "detail",
  RECOMMENDED: "recommended",
  "MORE-RECOMMENDATION": "more-recommendation",
  LOGIN: "login",
  SIGNUP: "signup",
  HOME: "/",
  DASHBOARD: "dashboard",
  AI_CHAT: "ai-chat",
  SAVE_RESOURCES: "save-resources",
  EDITOR_CARE_PLAN: "editor/care-plan",
  EDITOR_VIEW_PLAN: "editor/view-plan",
}
