export const ALL_ROUTES = {
  ORG: "org",
  RESULTS: "results",
  DETAIL: "detail",
  RECOMMENDED: "recommended",
  "MORE-RECOMMENDATION": "more-recommendation",
  SIGNIN: "signin",
  "RECENT-LOGIN": "recent-login",
  SIGNUP: "signup",
  SIGNUP_STEPS: {
    SIGNUP: "signup",
    WHO_ARE_YOU: "who_are_you",
    CREATE_PROFILE: "create_profile",
    CREATE_PROFILE1: "create_profile1",
    CREATE_PROFILE2: "create_profile2",
    TELL_US_YOUR_STORY: "tell_us_your_story",
    REVIEW_AND_SAVE: "review_and_save",
    FINISH: "finish",
  },
  HOME: "/",
  DASHBOARD: "dashboard",
  AI_CHAT: "ai-chat",
  SAVE_RESOURCES: "save-resources",
  EDITOR_CARE_PLAN: "editor/care-plan",
  EDITOR_VIEW_PLAN: "editor/view-plan",
}
