export const DATA_ORG_KeyNamesForCards_D = {
  KEY_NAME: "key",
  VALUE_NAME: "data",
  THIRD_PAGE_DATA: "thirdPageData",
  FOLDER_NAME: "folderName",
  CARD: "card",
  WITH_BACKGROUND: "withBackground",
  LEFT: "left",
  RIGHT: "right",
  HIGHLIGHT: "highlight",
  HIGHLIGHT_PLUS: "highlight_plus",
  DISPLAY_BLOCK: "display_block",
}

export const enum DATA_ORG_KeyNamesForCards_D_KEYS {
  KEY_NAME = "key",
  VALUE_NAME = "data",
  THIRD_PAGE_DATA = "thirdPageData",
  FOLDER_NAME = "folderName",
  CARD = "card",
  WITH_BACKGROUND = "withBackground",
  LEFT = "left",
  RIGHT = "right",
  HIGHLIGHT = "highlight",
  HIGHLIGHT_PLUS = "highlight_plus",
  DISPLAY_BLOCK = "display_block",
  GET_FILTER_THIRDPAGE_DATAONOBJECT = "getFilterThirdPageDataOnObject",
  OTHER = "other",
  USERS_ALSO_VIEWES = "USERS_ALSO_VIEWES",
  JOB_DESCRIPTION = "JOB_DESCRIPTION",
  RESPONSABILITIES = "RESPONSABILITIES",
  SECTIONS = "SECTIONS",
  NAVIGATION_BAR = "NAVIGATION_BAR",
  TOOLTIP = "TOOLTIP",
  LAYOUT_MAIN_CARD_RIGHT = "LAYOUT_MAIN_CARD_RIGHT",
  HOW_IS_MAP = "HOW_IS_MAP",
  CONTACT_US_CUSTOM_PROPERTIES = "CONTACT_US_CUSTOM_PROPERTIES",
}
