import { FC } from "react"

export const enum BRAND_OPTION_DEFAULT {
  DEFAULT = "DEFAULT",
}

type BRAND_OPTIONS = FC | BRAND_OPTION_DEFAULT

export const enum SPECIFIC_DATA_KEY {
  SPECIFIC_DATA_KEY = "SPECIFIC_DATA_KEY",
  BUTTON_TO_THIRDPAGE_NAME = "BUTTON_TO_THIRDPAGE_NAME",
  SVG = "SVG",
  BRAND = "BRAND",
}

export type Structure_SpecificData = {
  [SPECIFIC_DATA_KEY.BUTTON_TO_THIRDPAGE_NAME]: string
  [SPECIFIC_DATA_KEY.SVG]: BRAND_OPTIONS
  [SPECIFIC_DATA_KEY.BRAND]?: string
}
