name: "Test Vitest plus React-Testing-Library"

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: "Testing: vitest and react testing library"
    runs-on: ubuntu-22.04
    steps:
      - name: get last commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: run npm ci
        run: npm ci
      - name: run npm test
        run: npm test
